name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clonar o reposit√≥rio
        uses: actions/checkout@v4

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: MateusPilonetto
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: For√ßar o salvamento no GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist'
          message: 'üêç Atualizando a cobrinha'
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
